[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=()"
    # Regla de Redirecci√≥n para el subdominio de la oferta
[[redirects]]
  from = "/*"
  to = "/oferta.html"
  status = 200
  force = true
  [redirects.conditions]
    Host = "oferta.luisantonio.com.ve"
